Add murate support and refactor scripts

diff --git a/target/add-ons/fs/usr/local/bin/emerson12vOFF b/target/add-ons/fs/usr/local/bin/emerson12vOFF
--- a/target/add-ons/fs/usr/local/bin/emerson12vOFF
+++ b/target/add-ons/fs/usr/local/bin/emerson12vOFF
@@ -23,22 +23,53 @@ echo TOP ${TOP} , BOT ${BOTTOM}
 
 ERR=0
 
+SET_ADDR_CMD ()
+{
+    if  [ "${PNR:2:4}" == "1050" ] ; then
+        echo ${PSU_NAME} EMERSON 1050
+        ADDR=0x5f
+        ON_CMD=0x80
+        OFF_CMD=0x40
+    elif [ "${PNR:2:4}" == "1200" ] ; then
+        echo ${PSU_NAME} EMERSON 1200
+        ADDR=0x3f
+        ON_CMD=0x80
+        OFF_CMD=0x40
+    elif [ "${PNR:0:5}" == "1U3CS" ] ; then
+        echo ${PSU_NAME} NEW MURATA
+        ADDR=0x5f
+        ON_CMD=0x80
+        OFF_CMD=0x00
+    else
+        echo "${PSU_NAME} NOT EMERSON!! AC2DC CANT TOGGLE POWER"
+        ERR=$((${ERR}+${PSU_ADDR}))
+    fi
+
+}
+
+PWR_ON ()
+{
+
+    i2cset -y 0 0x70 ${PSU_ADDR}
+    i2cset -y 0 ${ADDR} 0x01 ${ON_CMD} 
+    sleep 2
+
+    #verify ON (can access i2c 0x71)
+    i2cset -y 0 0x70 ${BRD_ADDR}
+    i2cset -y 0 0x71 0x00 > /dev/null 2>&1
+    if [ $? -ne 0 ] ; then
+        echo "12v OFF - oh oh , failed to power ${PSU_NAME} 12v UP!"
+        ERR=$((${ERR}+${PSU_ADDR}))
+    else
+        echo "${PSU_NAME} 12v ON, GOOD! "
+    fi
+}
+
 PWR_OFF ()
 {
-        if  [ "${PNR:2:4}" == "1050" ] ; then
-                echo ${PSU_NAME} EMERSON 1050
-                ADDR=0x5f
-        elif [ "${PNR:2:4}" == "1200" ] ; then
-                echo ${PSU_NAME} EMERSON 1200
-                ADDR=0x3f
-        else
-                echo "${PSU_NAME} NOT EMERSON!! AC2DC CANT TOGGLE POWER"
-                ERR=$((${ERR}+${PSU_ADDR}))
-        fi
-
         i2cset -y 0 0x70 ${PSU_ADDR}
-        i2cset -y 0 ${ADDR} 0x10 0x00
-        i2cset -y 0 ${ADDR} 0x01 0x40
+        i2cset -y 0 ${ADDR} 0x10 0x00 > /dev/null 2>&1
+        i2cset -y 0 ${ADDR} 0x01 ${OFF_CMD}
         sleep 2
 
         #verify OFF (cant access i2c 0x71)
@@ -50,7 +81,6 @@ PWR_OFF ()
                 echo "12v ON. oh oh Failed ot put ${PSU_NAME} 12V OFF"
                 ERR=$((${ERR}+${PSU_ADDR}))
         fi
-
 }
 
 if [ ${TOP} -eq 1 ] ; then
@@ -58,15 +88,24 @@ if [ ${TOP} -eq 1 ] ; then
         PSU_ADDR=0x10
         BRD_ADDR=0x04
         PSU_NAME=TOP
-        PWR_OFF
+        SET_ADDR_CMD
+        if [ ${ERR} -eq 0 ] ; then
+            PWR_OFF
+        fi
 fi        
 
 if [ ${BOTTOM} -eq 1 ] ; then
+        OLDERR=${ERR}                        
+        ERR=0
         PNR=`ac2dcvpd -bottom -p -q 2>/dev/null`
         PSU_ADDR=0x01
         BRD_ADDR=0x08
         PSU_NAME=BOTTOM
-        PWR_OFF
+        SET_ADDR_CMD
+        if [ ${ERR} -eq 0 ] ; then
+            PWR_OFF
+        fi
+        ERR=$((${ERR}+${OLDERR}))
 fi        
 
 exit ${ERR}
